/// Use Case: Create Warranty
///
/// Sprint 1: SCRUM-865 (Manual Warranty Entry Form)
/// Validates input and creates a warranty entity.

import 'package:warranty_shield/domain/entities/warranty_entity.dart';
import 'package:warranty_shield/domain/repositories/warranty_repository.dart';

class CreateWarrantyUseCase {
  final WarrantyRepository repository;

  CreateWarrantyUseCase(this.repository);

  Future<WarrantyEntity> call({
    required String productName,
    required DateTime purchaseDate,
    required int warrantyDurationMonths,
    required String retailer,
    required double price,
    required String userId,
  }) {
    // Validate inputs
    _validateInputs(
      productName: productName,
      purchaseDate: purchaseDate,
      warrantyDurationMonths: warrantyDurationMonths,
      retailer: retailer,
      price: price,
    );

    final expirationDate = purchaseDate.add(
      Duration(days: warrantyDurationMonths * 30.44),
    );

    final warranty = WarrantyEntity(
      id: '', // Generated by backend
      userId: userId,
      productName: productName.trim(),
      purchaseDate: purchaseDate,
      warrantyDurationMonths: warrantyDurationMonths,
      retailer: retailer.trim(),
      price: price,
      expirationDate: expirationDate,
      createdAt: DateTime.now(),
      status: WarrantyEntity.calculateStatus(expirationDate),
    );

    return repository.createWarranty(warranty);
  }

  void _validateInputs({
    required String productName,
    required DateTime purchaseDate,
    required int warrantyDurationMonths,
    required String retailer,
    required double price,
  }) {
    if (productName.trim().isEmpty) {
      throw ArgumentError('Product name is required');
    }
    if (purchaseDate.isAfter(DateTime.now())) {
      throw ArgumentError('Purchase date cannot be in the future');
    }
    if (purchaseDate.isBefore(DateTime.now().subtract(const Duration(days: 3650)))) {
      throw ArgumentError('Purchase date cannot be more than 10 years ago');
    }
    if (warrantyDurationMonths <= 0) {
      throw ArgumentError('Warranty duration must be positive');
    }
    if (retailer.trim().isEmpty) {
      throw ArgumentError('Retailer is required');
    }
    if (price <= 0) {
      throw ArgumentError('Price must be positive');
    }
  }
}